package com.ericsson.mgre.biz.networkMgmt.element.config;

/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

//import javax.ejb.EJBLocalObject;


public interface FasciaTariffaria {
  public String getCodFascia() ;
  public String getDescrizioneFascia() ;
  public void setCodFascia(String val) ;
  public void setDescrizioneFascia(String val) ;
}
