package com.ericsson.mgre.biz.networkMgmt.element.config;

/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

import javax.ejb.EJBLocalObject;


public interface TipologiaInstallazione extends EJBLocalObject {
  public String getCodTipmodin() ;
  public String getDesTipmodin() ;
  public void setCodTipmodin(String val) ;
  public void setDesTipmodin(String val) ;
}
