package com.ericsson.mgre.biz.reductionsMgmt.reductions;


/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

import java.io.Serializable;

final public class ConfigAlleggProgrBeanPK implements Serializable {
  public String codConfigAll;
  public String giornoSettimana;

  public ConfigAlleggProgrBeanPK() {}

  public ConfigAlleggProgrBeanPK(String codConfigAll, String giornoSettimana) {
    this.codConfigAll = codConfigAll;
    this.giornoSettimana = giornoSettimana;

  }

  private int m_hashCode = 0;
  public int hashCode() {
    if (0 == m_hashCode) {
      m_hashCode = (codConfigAll.hashCode()) ^ (giornoSettimana.hashCode());
    }
    return m_hashCode;
  }

  public boolean equals(Object other) {
    if (other == this) return true;
    if (null == other) return false;
    if (other.hashCode() != hashCode()) return false;
    try {
      ConfigAlleggProgrBeanPK other2 = (ConfigAlleggProgrBeanPK) other;
      return (this.codConfigAll.equals(other2.codConfigAll)) && (this.giornoSettimana.equals(other2.giornoSettimana));
    }
    catch(ClassCastException ex) {
      return false;
    }


  }
  public String toString() { 
    StringBuffer result = new StringBuffer("[ConfigAlleggProgrBeanPK ");
    result.append("codConfigAll:" + (null == codConfigAll ? "null" : codConfigAll.toString())).append(" ");
    result.append("giornoSettimana:" + (null == giornoSettimana ? "null" : giornoSettimana.toString())).append(" ");
    result.append("]");
    return result.toString();
  }

}
