package com.ericsson.mgre.biz.reductionsMgmt.reductions;

/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

//import javax.ejb.EJBLocalObject;


public interface ConfigAlleggEmerg {
  public Long getCoeffLimitazione() ;
  public void setCoeffLimitazione(Long val) ;
}
