package com.ericsson.mgre.biz.reductionsMgmt.reductions;

/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

//import javax.ejb.EJBLocalObject;


// public interface ProgressiviLiberati extends EJBLocalObject {
public interface ProgressiviLiberati {
  public String getCodGruppoApplicativo() ;
  public Long getProgrLiberato() ;
  public void setCodGruppoApplicativo(String val) ;
  public void setProgrLiberato(Long val) ;
}
