package com.ericsson.mgre.biz.reductionsMgmt;


/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;

public interface AlleggerimentiFacadeLocalHome extends EJBLocalHome {
  public AlleggerimentiFacadeLocal create()     throws CreateException;
}
