package com.ericsson.mgre.biz.reductionsMgmt;


/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

import java.rmi.RemoteException;

import javax.ejb.CreateException;
import javax.ejb.EJBHome;

public interface AlleggerimentiFacadeHome extends EJBHome {
  public AlleggerimentiFacade create()     throws CreateException, RemoteException;

}
