package com.ericsson.mgre.biz.networkMgmt.element;

/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

import javax.ejb.EJBLocalObject;


public interface CabinaSecondaria extends EJBLocalObject {
  public String getCodCabinaSecondaria() ;
  public String getCodDensita() ;
  public String getCodZona() ;
  public String getIndirizzoCabina() ;
  public String getNomeCabina() ;
  public String getNote() ;
  public String getStatoGuasto() ;
  public void setCodCabinaSecondaria(String val) ;
  public void setCodDensita(String val) ;
  public void setCodZona(String val) ;
  public void setIndirizzoCabina(String val) ;
  public void setNomeCabina(String val) ;
  public void setNote(String val) ;
  public void setStatoGuasto(String val) ;
}
