package com.ericsson.mgre.biz.networkMgmt.element;


/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

import java.util.Collection;

import javax.ejb.CreateException;
import javax.ejb.EJBLocalHome;
import javax.ejb.FinderException;

public interface CabinaSecondariaHome extends EJBLocalHome {
  public Collection findAll()     throws FinderException;
  public Collection findByCodDensita(String codDensita)     throws FinderException;
  public Collection findByCodZona(String codZona)     throws FinderException;
  public CabinaSecondaria findByPrimaryKey(String primaryKey)     throws FinderException;
  public CabinaSecondaria create(String codCabinaSecondaria)     throws CreateException;
}
