package com.ericsson.mgre.biz.networkMgmt.element;

/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

//import javax.ejb.EJBLocalObject;


public interface LenntCliente {
	
  public String getAnnoFabbricazione() ;
  public String getCaratteristicaInstallazione() ;
  public String getCodCabinaSecondaria() ;
  public String getCodConcentratore() ;
  // Modifica R01
  public String getCodConcentratore2();
  public String getCodConcentratore3();
  // end
  public Integer getUtenzaSpeciale() ;
  public String getCodConfigAll() ;
  public String getCodGruppoApplicativo() ;
  public Long getCodLineaBt() ;
  public String getCodPosizione() ;
  public Long getCodSezione() ;
  public String getCodTipmodin() ;
  public String getCodTiputt() ;
  public Long getCoeffLimitazione() ;
  public String getCostruttore() ;
  public String getFase() ;
  public Long getFlagAbilitazione() ;
  public Long getFlagRipetitore() ;
  public String getGuastoLennt() ;
  public Integer getIndirizzo() ;
  public String getLingua() ;
  public String getMatrDistrEnerg() ;
  public String getMatricolaLenntCliente() ;
  public String getNumeroUtenza() ;
  public String getNumtelGuasti() ;
  public String getNumtelInfo() ;
  public String getPresenzaDatiSegr() ;
  public Long getProgrLenntGruppo() ;
  public String getProgressivoAnno() ;
  public String getRaggiungLennt() ;
  public String getReleaseFirmware() ;
  public String getStatoAlleggEmerg() ;
  public String getStatoAlleggProgr() ;
  public String getTipo() ;
  public String getTipoAlimentazione() ;
  public java.util.Date getUltimoContatto() ;
  public String getTipoAssegnazione();
  
  
  
  public void setAnnoFabbricazione(String val) ;
  public void setCaratteristicaInstallazione(String val) ;
  public void setCodCabinaSecondaria(String val) ;
  public void setCodConcentratore(String val) ;
  // Modifca R01
  public void setCodConcentratore2(String val) ;
  public void setCodConcentratore3(String val) ;
  // end
  public void setUtenzaSpeciale(Integer val) ;
  public void setCodConfigAll(String val) ;
  public void setCodGruppoApplicativo(String val) ;
  public void setCodLineaBt(Long val) ;
  public void setCodPosizione(String val) ;
  public void setCodSezione(Long val) ;
  public void setCodTipmodin(String val) ;
  public void setCodTiputt(String val) ;
  public void setCoeffLimitazione(Long val) ;
  public void setCostruttore(String val) ;
  public void setFase(String val) ;
  public void setFlagAbilitazione(Long val) ;
  public void setFlagRipetitore(Long val) ;
  public void setGuastoLennt(String val) ;
  public void setIndirizzo(Integer val) ;
  public void setLingua(String val) ;
  public void setMatrDistrEnerg(String val) ;
  public void setMatricolaLenntCliente(String val) ;
  public void setNumeroUtenza(String val) ;
  public void setNumtelGuasti(String val) ;
  public void setNumtelInfo(String val) ;
  public void setPresenzaDatiSegr(String val) ;
  public void setProgrLenntGruppo(Long val) ;
  public void setProgressivoAnno(String val) ;
  public void setRaggiungLennt(String val) ;
  public void setReleaseFirmware(String val) ;
  public void setStatoAlleggEmerg(String val) ;
  public void setStatoAlleggProgr(String val) ;
  public void setTipo(String val) ;
  public void setTipoAlimentazione(String val) ;
  public void setUltimoContatto(java.util.Date val) ;
  public void setTipoAssegnazione(String val); 
}
