package com.ericsson.mgre.biz.networkMgmt.element;


/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

import java.io.Serializable;

final public class LenntConcentratoreBeanPK implements Serializable {
  public String codConcentratore;
  public java.util.Date dataAssoc;
  public String matricolaLenntCliente;

  public LenntConcentratoreBeanPK() {}

  public LenntConcentratoreBeanPK(String codConcentratore, java.util.Date dataAssoc, String matricolaLenntCliente) {
    this.codConcentratore = codConcentratore;
    this.dataAssoc = dataAssoc;
    this.matricolaLenntCliente = matricolaLenntCliente;

  }

  private int m_hashCode = 0;
  public int hashCode() {
    if (0 == m_hashCode) {
      m_hashCode = (codConcentratore.hashCode()) ^ (dataAssoc.hashCode()) ^ (matricolaLenntCliente.hashCode());
    }
    return m_hashCode;
  }

  public boolean equals(Object other) {
    if (other == this) return true;
    if (null == other) return false;
    if (other.hashCode() != hashCode()) return false;
    try {
      LenntConcentratoreBeanPK other2 = (LenntConcentratoreBeanPK) other;
      return (this.codConcentratore.equals(other2.codConcentratore)) && (this.dataAssoc.equals(other2.dataAssoc)) && (this.matricolaLenntCliente.equals(other2.matricolaLenntCliente));
    }
    catch(ClassCastException ex) {
      return false;
    }


  }
  public String toString() { 
    StringBuffer result = new StringBuffer("[LenntConcentratoreBeanPK ");
    result.append("codConcentratore:" + (null == codConcentratore ? "null" : codConcentratore.toString())).append(" ");
    result.append("dataAssoc:" + (null == dataAssoc ? "null" : dataAssoc.toString())).append(" ");
    result.append("matricolaLenntCliente:" + (null == matricolaLenntCliente ? "null" : matricolaLenntCliente.toString())).append(" ");
    result.append("]");
    return result.toString();
  }

}
