package com.ericsson.mgre.biz.networkMgmt.element;

/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

import javax.ejb.EJBLocalObject;


public interface LenntTrasformatore extends EJBLocalObject {
  public String getCodConcentratore() ;
  public Long getCodSbarraBt() ;
  public String getMatricolaLennt() ;
  public String getRaggiungLennt() ;
  public String getStatoLennt() ;
  public java.util.Date getUltimoContatto() ;
  public void setCodConcentratore(String val) ;
  public void setCodSbarraBt(Long val) ;
  public void setMatricolaLennt(String val) ;
  public void setRaggiungLennt(String val) ;
  public void setStatoLennt(String val) ;
  public void setUltimoContatto(java.util.Date val) ;
}
