package com.ericsson.mgre.biz.networkMgmt.element;

/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

// import javax.ejb.EJBLocalObject;


public interface LenntConcentratore {
  public String getCodConcentratore() ;
  public java.util.Date getDataAssoc() ;
  public String getMatricolaLenntCliente() ;
  public void setCodConcentratore(String val) ;
  public void setDataAssoc(java.util.Date val) ;
  public void setMatricolaLenntCliente(String val) ;
}
