package com.ericsson.mgre.biz.networkMgmt;

/*
  ** This file was automatically generated by EJBGen 2.15 beta - Workshop 8.1
  ** Build: 20030408-0944
*/

import java.rmi.RemoteException;

//import javax.ejb.EJBObject;

public interface ConfigurazioniFacade {
  public com.ericsson.mgre.biz.networkMgmt.element.config.DensitaDTO[] getAllDensita()     throws RemoteException, javax.ejb.FinderException, Exception;

  public com.ericsson.mgre.biz.networkMgmt.element.config.FasciaTariffariaDTO[] getAllFasciaTariffaria()     throws RemoteException, javax.ejb.FinderException, Exception;

  public com.ericsson.mgre.biz.networkMgmt.element.config.TipoUtenteDTO[] getAllTipoUtente()     throws RemoteException, javax.ejb.FinderException, Exception;

  public com.ericsson.mgre.biz.networkMgmt.element.config.TipologiaInstallazioneDTO[] getAllTipologiaInstallazione()     throws RemoteException, javax.ejb.FinderException, Exception;

  public com.ericsson.mgre.biz.networkMgmt.element.config.ZonaDTO[] getAllZona()     throws RemoteException, javax.ejb.FinderException, Exception;

  public com.ericsson.mgre.biz.networkMgmt.element.config.DensitaDTO getDensita(String codDensita)     throws RemoteException, javax.ejb.FinderException, Exception;

  public com.ericsson.mgre.biz.networkMgmt.element.config.FasciaTariffariaDTO getFasciaTariffaria(String codFascia)     throws RemoteException, javax.ejb.FinderException, Exception;

  public com.ericsson.mgre.biz.networkMgmt.element.config.TipoUtenteDTO getTipoUtente(String codTiput)     throws RemoteException, javax.ejb.FinderException, Exception;

  public com.ericsson.mgre.biz.networkMgmt.element.config.TipologiaInstallazioneDTO getTipologiaInstallazione(String codTipmodin)     throws RemoteException, javax.ejb.FinderException, Exception;

  public com.ericsson.mgre.biz.networkMgmt.element.config.ZonaDTO getZona(String codZona)     throws RemoteException, javax.ejb.FinderException, Exception;

}
