package com.ericsson.urm.xml.webmenu;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.05.11 at 10:54:10 AM CEST
//


import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for menutype complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="menutype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="node" type="{http://www.ericsson.com/URM_MENU}node-type" maxOccurs="unbounded"/>
 *         &lt;element name="leaf" type="{http://www.ericsson.com/URM_MENU}leaf-type" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="default-authorization" type="{http://www.ericsson.com/URM_MENU}authorization-type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "menutype", propOrder = {
        "node",
        "leaf",
        "defaultAuthorization"
})
public class Menutype {

    @XmlElement(required = true)
    protected List<NodeType> node;
    protected List<LeafType> leaf;
    @XmlElement(name = "default-authorization", required = true)
    protected AuthorizationType defaultAuthorization;

    /**
     * Gets the value of the node property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the node property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNode().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NodeType }
     *
     *
     */
    public List<NodeType> getNode() {
        if (node == null) {
            node = new ArrayList<NodeType>();
        }
        return this.node;
    }

    /**
     * Gets the value of the leaf property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leaf property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLeaf().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LeafType }
     *
     *
     */
    public List<LeafType> getLeaf() {
        if (leaf == null) {
            leaf = new ArrayList<LeafType>();
        }
        return this.leaf;
    }

    /**
     * Gets the value of the defaultAuthorization property.
     *
     * @return
     *     possible object is
     *     {@link AuthorizationType }
     *
     */
    public AuthorizationType getDefaultAuthorization() {
        return defaultAuthorization;
    }

    /**
     * Sets the value of the defaultAuthorization property.
     *
     * @param value
     *     allowed object is
     *     {@link AuthorizationType }
     *
     */
    public void setDefaultAuthorization(AuthorizationType value) {
        this.defaultAuthorization = value;
    }

}
