//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.11 at 10:54:10 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ericsson.com/URM_MENU", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ericsson.urm.xml.webmenu;
